FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64"  alpineversion="3.9.0" build="05-Feb-2019"

ADD alpine-minirootfs-3.9.0-x86_64.tar.gz /
CMD ["/bin/sh"]
