FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64"  alpineversion="3.8.0" build="20-sep-2018"

ADD alpine-minirootfs-3.8.0-x86_64.tar.gz /
CMD ["/bin/sh"]
