FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM64v8/aarch64"  alpineversion="3.8.0" build="20-sep-2018"

ADD alpine-minirootfs-3.8.0-aarch64.tar.gz /
CMD ["/bin/sh"]
