FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64"  alpineversion="3.8.1" build="01-jan-2019"

ADD alpine-minirootfs-3.8.1-x86_64.tar.gz /
CMD ["/bin/sh"]
