FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM64v8/aarch64"  alpineversion="3.8.2" build="05-Feb-2019"

ADD alpine-minirootfs-3.8.2-aarch64.tar.gz /
CMD ["/bin/sh"]
