FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM64v8/aarch64"  alpineversion="3.9.0" build="05-Feb-2019"

ADD alpine-minirootfs-3.9.0-aarch64.tar.gz /
CMD ["/bin/sh"]
