FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM32v7/armhf"  alpineversion="3.9.0" build="05-Feb-2019"

ADD alpine-minirootfs-3.9.0-armhf.tar.gz /
CMD ["/bin/sh"]
