FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM32v7/armhf"  alpineversion="3.8.1" build="20-sep-2018"

ADD alpine-minirootfs-3.8.1-armhf.tar.gz /
CMD ["/bin/sh"]
