FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM32v7/armhf"  alpineversion="3.7.0" build="21122017"

ADD alpine-minirootfs-3.7.0-armhf.tar.gz /
CMD ["/bin/sh"]
