FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM32v7/armhf"  alpineversion="3.8.2" build="05-Feb-2019"

ADD alpine-minirootfs-3.8.2-armhf.tar.gz /
CMD ["/bin/sh"]
