FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM64v8/aarch64"  alpineversion="3.7.0" build="21122017"

ADD alpine-minirootfs-3.7.0-aarch64.tar.gz /
CMD ["/bin/sh"]
