FROM scratch
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64"  alpineversion="3.7.0" build="21122017"

ADD alpine-minirootfs-3.7.0-x86_64.tar.gz /
CMD ["/bin/sh"]
